### ISSUE TITLE
Unverified Accounts

### ISSUE THREAD

**Issue by Naviary2** [Infinite-Chess/infinitechess.org#1]
Unverified accounts are never deleted! This can create issues with:
* Spamming new accounts.
* Creating accounts using someone else's email, without their consent.

## Proposal ##

Set an interval, every 24 hours, to iterate through all members. If they are not verified, and their join date is over 3 days ago, auto-delete their account.

**Comment by siddpra0** [comment]
For the second one you can do OTP? OTP are used everywhere so just send a OTP to the gmail and ask for that?

**Comment by jermOSS** [comment]
I'm just curious why even allow accounts with unverified email in the first place?

**Comment by Naviary2** [comment]
> I'm just curious why even allow accounts with unverified email in the first place?

I don't have a holding cell for unverified accounts, just a flag in the members json data that says they are not verified.

**Comment by Nul-led** [comment]
The real solution to this is to simply force email verification during registration. Another option is to track latest logins, which allows discarding old accounts in general, maybe unverified accounts with a smaller timespan than verified ones.

**Comment by Naviary2** [comment]
I do have a `seen` property which keeps track of the last time they were seen. But that's a tad different from last "login".

**Comment by Naviary2** [comment]
Fixed with the help of @shacharrr, in #82 !
