### ISSUE TITLE
Game code metadata should match that of Lichess.org

### ISSUE THREAD

**Issue by Naviary2** [Infinite-Chess/infinitechess.org#119]
Currently the game's ICN's, or game code's, metadata is different from that of [Lichess.org](https://database.lichess.org/) (scroll down to "Sample"). If we want to be consistent with norms, we should probably convert!

An example of the metadata of an ICN (Infinite Chess Notation) metadata now is:

```
[Variant: Knighted Chess]
[White: Owner]
[Black: aaa]
[Clock: 10+4]
[Date: 2024/07/22 05:42:12]
[Result: 0-1]
[Condition: Resignation]
[Rated: No]
```

An example of Lichess's metadata is:

```
[Event "Rated Bullet tournament https://lichess.org/tournament/yc1WW2Ox"]
[Site "https://lichess.org/PpwPOZMq"]
[Date "2017.04.01"]
[Round "-"]
[White "Abbot"]
[Black "Costello"]
[Result "0-1"]
[UTCDate "2017.04.01"]
[UTCTime "11:32:01"]
[WhiteElo "2100"]
[BlackElo "2000"]
[WhiteRatingDiff "-4"]
[BlackRatingDiff "+1"]
[WhiteTitle "FM"]
[ECO "B30"]
[Opening "Sicilian Defense: Old Sicilian"]
[TimeControl "300+0"]
[Termination "Time forfeit"]
```

Some of these aren't relevant to us yet, but there are others which match metadata we have now.

**Comment by tsevasa** [comment]
I can take care of updating formatconverter.js since I wrote it.

**Comment by Naviary2** [comment]
Discussion here
https://discord.com/channels/1114425729569017918/1265042653037465714

**Comment by Naviary2** [comment]
I have resolved this. We now adopt most of these norms!
