### ISSUE TITLE
Change header and footer implementations 

### ISSUE THREAD

**Issue by life-enjoyer** [Infinite-Chess/infinitechess.org#12]
Currently the header and the footer are hardcoded in all the html pages that need them. It is not that big of an issue since they are not often changed but it would be better to have them written only once, especially considering that the number of pages will probably grow over time

**Comment by NoobJsPerson** [comment]
yea cool idea! [ejs](https://www.npmjs.com/package/ejs) could be used for this.

**Comment by this-is-not-available** [comment]
Would iframes work?

**Comment by HydrogenMacro** [comment]
iframes would be very inefficient and clunky, so I don't think that they would be the best option
