### ISSUE TITLE
Bug- When viewing opponent's legal moves, en passant shows as legal where they just double pushed a pawn.

### ISSUE THREAD

**Issue by Naviary2** [Infinite-Chess/infinitechess.org#130]
<img width="748" alt="Screen Shot 2024-07-25 at 2 37 23 PM" src="https://github.com/user-attachments/assets/56db56b2-eaad-4f2e-a617-9ef220da5218">

White-to-move

**Comment by tsevasa** [comment]
This should be fixed by #131. Now specialdetect.js only allows you to capture en passant if this would capture a piece of the opposing color.

**Comment by Naviary2** [comment]
Sweet!!!
