### ISSUE TITLE
Backend for settings

### ISSUE THREAD

**Issue by this-is-not-available** [Infinite-Chess/infinitechess.org#15]
We will inevitably need to store user settings (say, account visibility, description, custom colors).
So, we need a (preferably flexible) backend for getting/setting user's settings.

**Comment by Naviary2** [comment]
Yes! This could be done at the same time we add customizable color themes. [Discussion here](https://discord.com/channels/1114425729569017918/1260305825424085075)

A copy of user's settings can also be stored in browser storage so it's remembered after they logged out.

**Comment by Naviary2** [comment]
When themes are added we'll add user preferences. Then as more features come along we can add more preferences. I will close this as custom themes includes this feature.

**Comment by this-is-not-available** [comment]
While I do believe we will add preferences as we add custom themes, I don't think closing this issue as "completed" is the right choice.

**Comment by this-is-not-available** [comment]
It would be finished when there are some settings in place and a flexible way to add more settings and setting types.

**Comment by this-is-not-available** [comment]
This is done. Preferences are stored on the server and are stored as a flexible JSON string.

**Comment by Naviary2** [comment]
I will note however, the current preferences are public information, as anyone can access anyone other anyone else's preferences, so if we wanted to store anything sensitive like account settings, we'll have to either make it not public, or separate it into its own preferences thing.
