### ISSUE TITLE
Stricter password restrictions

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Infinite-Chess/infinitechess.org#20]
Currently, a password of `123456` is allowed even though `password` is not. 

# Proposal
Impose more restrictions on the passwords.
For everyone that already has a password set as a "weak" password, they will receive popups, notifications, or alerts advising them to change their password.

**Comment by life-enjoyer** [comment]
The passwords are hashed and salted so we can't know if someone already registered has a weak password.
But we could set more restrictions on newly created password such as having at least one special character, one uppercase letter and one number

**Comment by Heinrich-XIAO** [comment]
That could happen on login though.

**Comment by Naviary2** [comment]
Passwords are collected when logging in, so they can be checked for security at that time, they are neither saved, nor logged.

#19 Link to the pull request adding stronger password security requirements.

**Comment by Naviary2** [comment]
At this time, we won't enforce stricter password requirements. There isn't enough at stake if your account's hacked, and the website is still relatively small, don't want to scare people off. In the future we can revisit this!
