### ISSUE TITLE
Tab titles translation

### ISSUE THREAD

**Issue by Apsurt** [Infinite-Chess/infinitechess.org#206]
Currently tab titles are not translated to different languages. It should be quite easy to change.

Currently:
<img width="158" alt="image" src="https://github.com/user-attachments/assets/9d74c43a-370b-4a40-b34e-b4d9e8a3d67f">

How it could look like (in polish):
<img width="150" alt="image" src="https://github.com/user-attachments/assets/91a1eace-2c53-46c3-97c6-0da5c0f229f4">

**Comment by Naviary3** [comment]
Oh! Good point! We don't have the titles being translated yet.
