### ISSUE TITLE
Overhauling repository structure and global logic

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Infinite-Chess/infinitechess.org#24]
The repo structure is not very friendly for those that are just starting out as of right now. Changing the repo structure could help those that may have less experience working with express.js, node.js, and Javascript in general.

**Comment by Naviary2** [comment]
We have brainstormed a solution to this [here!](https://discord.com/channels/1114425729569017918/1260387860792741959)! A new fork, [restructure](https://github.com/Infinite-Chess/infinitechess.org/tree/restructure) has been created just to do this!

**Comment by tsevasa** [comment]
You are right that the repository structure needs an overhaul.

Below you can find the current plan we worked out on the discord sever for the new large-scale structure we want to work out. In particular, there will no longer be a separate `protected-owner` version. Instead we only want to have script files in `src` that we can automatically deploy to `dist`.

```
dist/
├── home/
│   ├── index.html
│   ├── style.min.css
│   └── script.min.js
├── play/
│   ├── index.html
│   ├── style.min.css
│   └── script.min.js
├── admin/
│   └── dashboard/
│       ├── index.html
│       ├── style.min.css
│       └── script.min.js
└── assets/
    └── imgs/
        ├── img1.webp
        └── img2.webp
src/
├── client/
│   ├── home /
│   │   ├── index.html
│   │   ├── scripts/
│   │   │   ├── script1.js
│   │   │   ├── script2.js
│   │   │   └── script3.js
│   │   └── styles/
│   │       ├── style1.css
│   │       └── style2.css
│   └── assets/
│       └── imgs/
│           ├── img1.png
│           └── img2.jpeg
└── server/
    ├── routes
    ├── middleware
    ├── controllers
    └── utils
database
logs
docs
```

**Comment by tsevasa** [comment]
The restructuring of the project is now completed.
