### ISSUE TITLE
Using tabs instead of spaces

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Infinite-Chess/infinitechess.org#258]
I think we should use tabs instead of spaces as tabs can look different based on preferences. In this case, consistency is not ideal as different programmers want different tab sizes. I use 2 spaces per tab while the code in the repo all use 4 spaces per "tab".

**Comment by Heinrich-XIAO** [comment]
Github also renders tabs like this, so consistency between tabs and spaces is important. 
![image](https://github.com/user-attachments/assets/604283a7-1354-462a-b87e-c0bc8611b39f)

**Comment by Heinrich-XIAO** [comment]
Github allows you to change tab size, but this only works when they are real \t characters 
![image](https://github.com/user-attachments/assets/b9243b5f-323d-47bb-88e3-dd992644ab92)

**Comment by Naviary2** [comment]
Valid arguments.

When you say tabs can look different depending on your preferences, are you only referring to the length of tabs, or are there additional customizations for tabs?

I do think the way github renders tabs is a good reason to switch, but you aren't actually having to hit your space bar 4 times every line are you? My tab auto-inserts 4 spaces.

**Comment by Heinrich-XIAO** [comment]
probably only the length on most editors, but in vim-like editors, I'm pretty sure I can change colour as well.

**Comment by Heinrich-XIAO** [comment]
> but you aren't actually having to hit your space bar 4 times every line are you? My tab auto-inserts 4 spaces.

Here in neovim, I do have to slam space unless I configure tab to do that for me, but I can't because all of my other projects use \t.

**Comment by Naviary2** [comment]
Adopted! All indentation in the project is now tabs instead of spaces.
