### ISSUE TITLE
Code Credits

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Infinite-Chess/infinitechess.org#270]
It seems like the code credits weren't updated since b069a8ef4b770d091b79261decf45e720ce4b1e8.

**Comment by Naviary2** [comment]
That section I intended to be for files/libraries downloaded from the internet

**Comment by Heinrich-XIAO** [comment]
ok

**Comment by Naviary2** [comment]
We definitely could add a patron-combo-contributor list on the site!
