### ISSUE TITLE
Nested arrays inside TOML files shows grammar warnings on some IDEs

### ISSUE THREAD

**Issue by Naviary2** [Infinite-Chess/infinitechess.org#277]
<img width="677" alt="Screen Shot 2024-10-19 at 7 40 54 PM" src="https://github.com/user-attachments/assets/1ab9a27f-d020-4a2c-ba1f-2cecd865dbcc">

**Comment by xa31er** [comment]
But it isn't actually discouraged in the docs.
https://toml.io/en/v1.0.0#array

**Comment by Naviary2** [comment]
> But it isn't actually discouraged in the docs. https://toml.io/en/v1.0.0#array

What editor do you use?

**Comment by xa31er** [comment]
Vscode

**Comment by Naviary2** [comment]
Oh, huh? I use vscode too and it doesn't give me a semantic error

**Comment by xa31er** [comment]
Yeah it doesn't bother me that much.
It's probably just an extension going crazy.

**Comment by Naviary2** [comment]
Screenshot of the error?

Do you have the eslint extension installed?

**Comment by xa31er** [comment]
I've solved it.
It was a setting in the extension "Allow mixed arrays"

**Comment by Naviary3** [comment]
Great!
