### ISSUE TITLE
Move language selector to page header

### ISSUE THREAD

**Issue by xa31er** [Infinite-Chess/infinitechess.org#278]
The way that it is now, it is likely that people will miss it, because it is tucked down at the bottom of the page.

**Comment by Naviary2** [comment]
I can't remember if the first time someone visits the site it auto-sets their preferred language or not.

**Comment by xa31er** [comment]
We could also use this opportunity to implement a settings menu and solve issues #101 and #102

**Comment by Naviary2** [comment]
I am wanting to overhaul the design of the website. I think I'll make the settings menu first though, I'll try to design it for longevity.

And yes, users language should be auto-selected the first time they visit the website. That *slightly* decreases the need to move the language selector to the header.. but perhaps in the future design overhaul we could add a globe icon for this

**Comment by xa31er** [comment]
Yeah , I don't think it's **that** urgent

**Comment by Naviary2** [comment]
This has already been implemented in the themes branch, but I'll wait to close this until it's merged.

**Comment by Naviary2** [comment]
Oh yeah this is done now, forgot about this lol.
~~The Themes update completed so many issues~~
