### ISSUE TITLE
Game no longer loads

### ISSUE THREAD

**Issue by jermOSS** [Infinite-Chess/infinitechess.org#32]
While loading I get `Uncaught TypeError: e is null` and I am not able to click any buttons.

I can't trace the issue since the code is minified and obfuscated.

~~I have suspicion that the problem is caused by this commit: https://github.com/Infinite-Chess/infinitechess.org/commit/f06c688fedd0e33a41df312b48b76882b16421de although I'm not 100% sure.~~

**Comment by life-enjoyer** [comment]
Will be fix by #24 as minified would be generated automatically

For now, everything should work correctly at `devversion/play`

**Comment by Naviary2** [comment]
Fixed, this was cause by this commit
https://github.com/Infinite-Chess/infinitechess.org/commit/4a0900956bcd7c53009458697f1943bfdbd1b92a

**Comment by Naviary2** [comment]
It was a case of javascript trying to reference the old ID of a document element that was changed.
