### ISSUE TITLE
Jump to arbitrary board location

### ISSUE THREAD

**Issue by optim-ally** [Infinite-Chess/infinitechess.org#33]
This would probably be more useful for board editing. The idea is to provide input fields for any pair of valid coordinates and jump to that position rather than having to scroll there.

The two obvious ways to implement this in the UI are
1. make the coordinate display editable
2. add new fields in a dedicated "Jump to Position" popup

Option 1 is cleaner IMO but 2 is more explicit.

**Comment by Naviary2** [comment]
This is waiting for infinite move distance

**Comment by Naviary2** [comment]
Actually, it's fine if this is added before, it just has to be disabled for online games and only enabled for local. Otherwise, people can break the game by reaching large distances instantaneously.

**Comment by frankm1870** [comment]
Fixed
