### ISSUE TITLE
Automatically minification

### ISSUE THREAD

**Issue by jermOSS** [Infinite-Chess/infinitechess.org#35]
How it is now, everything is manually and effectively uploaded to the repo twice.

This makes it hard to debug, increases risk of malicious code being contributed and is overall just a lot of pain.

## Proposal
I propose to make use of package like `uglify-js` to automatically compress all JavaScript (and possibly CSS and HTML).

**Comment by life-enjoyer** [comment]
This is already planned by #24 and we're currently working on it. We're discussing it in [this discord channel](https://discord.com/channels/1114425729569017918/1260387860792741959) if you want to help

**Comment by tsevasa** [comment]
The restructuring of the project is now completed! The minification and deployment now happens automatically with the use of terser. Check out the updated [navigation guide](https://github.com/Infinite-Chess/infinitechess.org/blob/main/docs/NAVIGATING.md).

**Comment by tsevasa** [comment]
I think just because no one with permissions got around to closing it yet.
