### ISSUE TITLE
Deleting Account doesn't require password

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Infinite-Chess/infinitechess.org#68]
Deleting an account does not ask for the user's password. If an adversary were to gain access the the user's session token, but not the user's password, that adversary would be able to delete the user's account.

**Comment by cycy98** [comment]
Maybe phone verification...
Because else we coulld brute force

**Comment by tsevasa** [comment]
Or rather, I would propose e-mail + password verification:
When a user clicks "Delete account", they get sent an email with a temporary link. If they visit the link, they can input their password, to get the account deleted.
This would nicely complement #1 as unverified accounts will get deleted automatically anyways after some time.

**Comment by Heinrich-XIAO** [comment]
> Maybe phone verification... Because else we coulld brute force

If #2 gets applied here, brute force won't be a big problem.

**Comment by Naviary2** [comment]
Actually, any hacker will be able to send a request directly to the delete account controller, only requiring the users login info. If we are going to require your password to delete your account, that form data needs to be sent **with the request** to delete your account, and the remove account controller will have to be updated.

**Comment by Naviary2** [comment]
Fixed by #89
