### ISSUE TITLE
Store piece sprites as vector graphics

### ISSUE THREAD

**Issue by tsevasa** [Infinite-Chess/infinitechess.org#69]
Lichess stores all its piece sprites as vector graphics (see [here](https://github.com/lichess-org/lila/tree/master/public/piece/cburnett), for example) and each piece is less than 1KB in file size. In contrast, [our spritesheet](https://github.com/Infinite-Chess/infinitechess.org/blob/main/src/client/img/game/spritesheet64_cburnett.png) is a png file and takes up 1MB in total.

We should also store piece sprites in svg format.

**Comment by Naviary2** [comment]
This would be great, and a huge performance boost!! As long as we can convert the vector graphics back into textures on startup!

**Comment by xa31er** [comment]
can i  get this assigned? I want to help with something simple, to get familiar with the project structure. Thanks.

**Comment by Naviary2** [comment]
All piece's have now been converted to an SVG! Next we can take steps towards using those svgs and re-forming the spritesheet on the client-side with them!

See discussion here
https://discord.com/channels/1114425729569017918/1261070585476288674

**Comment by Naviary2** [comment]
I imagine we would group all the classical pieces into one http request (as svgs are just text afterall, there has to be some way to split them into individual svgs eith javascript afterward), and other fairy pieces may or may not be in groups! Atleast, a pair of a black and white piece should atleast be merged into one request.

**Comment by Heinrich-XIAO** [comment]
> I imagine we would group all the classical pieces into one http request (as svgs are just text afterall, there has to be some way to split them into individual svgs eith javascript afterward), and other fairy pieces may or may not be in groups! Atleast, a pair of a black and white piece should atleast be merged into one request.

We could combine them in one big JSON object or something.

**Comment by Heinrich-XIAO** [comment]
![image](https://github.com/user-attachments/assets/d2470abd-a0fd-4fa2-a5ff-8ceddc98715b)

**Comment by Naviary2** [comment]
> ![image](https://private-user-images.githubusercontent.com/74563446/373872518-d2470abd-a0fd-4fa2-a5ff-8ceddc98715b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDczNTgsIm5iZiI6MTcyODE0NzA1OCwicGF0aCI6Ii83NDU2MzQ0Ni8zNzM4NzI1MTgtZDI0NzBhYmQtYTBmZC00ZmEyLWE1ZmYtOGNlZGRjOTg3MTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE2NTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjFhN2Y2ZmY3ZGEwMDFkNGRlNGZmNDVmODc0NDVmNjdlZDE2YWUyODcyN2Y0MTVmN2FiNjI3N2MxYzJlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fF67R9QP7XPyuKxE5mowGT5dW15-uH_MeHSivlikzR0)

Is this the time it takes the request the spritesheet?

**Comment by Heinrich-XIAO** [comment]
> > ![image](https://private-user-images.githubusercontent.com/74563446/373872518-d2470abd-a0fd-4fa2-a5ff-8ceddc98715b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDczNTgsIm5iZiI6MTcyODE0NzA1OCwicGF0aCI6Ii83NDU2MzQ0Ni8zNzM4NzI1MTgtZDI0NzBhYmQtYTBmZC00ZmEyLWE1ZmYtOGNlZGRjOTg3MTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE2NTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjFhN2Y2ZmY3ZGEwMDFkNGRlNGZmNDVmODc0NDVmNjdlZDE2YWUyODcyN2Y0MTVmN2FiNjI3N2MxYzJlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fF67R9QP7XPyuKxE5mowGT5dW15-uH_MeHSivlikzR0)
> 
> Is this the time it takes the request the spritesheet?

Yeah. The 1MB file.

**Comment by Naviary2** [comment]
We don't even need to combine them all. If 95% of games are classical, we can just merge all the classical piece's svgs into one request, and only send the other fairy pieces when needed

**Comment by Naviary2** [comment]
All pieces have already been converted into SVG's and been compressed. All we need to do from here is:

* Write a method JavaScript method that will take a list of SVGs and create a spritesheet PNG from them (*maybe* could use inspiration from checkerboardgenerator.js?? Idk, ask ChatGPT how to do this)
* Merge all the classical piece SVGs into one API request.
* Create APIs for fetching all the other fairy pieces.

**Comment by Naviary2** [comment]
I'm going to start on this. I'm writing an outline of what I need to do:

1. Write an API route or create a resource that contains all the classical piece svgs in one text document.

2. Do the same, but one API/resource for each pair of white & black fairy pieces.

3. Load the classical piece svgs upon loading the play page.

4. Figure out how to use javascript to convert an svg into a texture.

5. Write a script for converting any number of input svgs into a large spritesheet image of any dimensions.

6. Upon loading a new game. Fetch the required svgs, then use the above script to create a spritesheet for that game. Perhaps I need some sort of loading animation if there's a delay.

**Comment by Naviary2** [comment]
The classical piece svgs take up just 9KB

**Comment by Heinrich-XIAO** [comment]
Why do we have to convert it into a PNG spritesheet? Isn't one of the main benefits of using SVGs (Scalable Vector Graphics) the scalability?

**Comment by Naviary2** [comment]
> Why do we have to convert it into a PNG spritesheet? Isn't one of the main benefits of using SVGs (Scalable Vector Graphics) the scalability?

WebGL can't directly render vector graphics. BUT, we can create a texture of any resolution out of an svg. I've programmed the spritesheet generator to aim to make the spritesheet large enough so that each image is atleast 512 pixels. That is more than enough for crisp clarity at all zoom levels. The spritesheet size won't exceed the maximum size supported by your device, but that number is VERY big for most devices.

**Comment by Naviary2** [comment]
The current spritesheet size has all the pieces at a width of 256 pixels, and there's a little bit of fuzziness when zooming in. But doubling this looks *great*!

**Comment by Naviary2** [comment]
#374 Added the majority of these features. All that remains now is to add an error message to the loading animation if by chance the page fails to load the svgs for a loaded game.

**Comment by Naviary2** [comment]
Okay an error message not shows if one of the fetch requests fail during spritesheet generation. However there isn't a retry button or automatic-refreshal, it just asks you to refresh. If you try to leave the game while the error message is up it totally breaks it.
