### ISSUE TITLE
Converting .png to .webp

### ISSUE THREAD

**Issue by tte0** [Infinite-Chess/infinitechess.org#79]
Converting images in main menu that have .png format to .webp format can increase performance a bit (especially in guide section) and gives more accessability.

edit: this can be aplied to most images

**Comment by Naviary2** [comment]
Yes! This could be discussed here! 
https://discord.com/channels/1114425729569017918/1260387860792741959

We could also concatenate all the game scripts into one big one!

**Comment by Naviary2** [comment]
This has been implemented!
