### ISSUE TITLE
Add customizable board colors and textures

### ISSUE THREAD

**Issue by Naviary2** [Infinite-Chess/infinitechess.org#84]
The game is lacking a lot of color! White and grey may not appeal to everyone. This I believe is one of **the most important next features**, and one that would attract more people, including streamers, to try out the game! We need a good first impression on people. Suggestion:

Add a gear-icon in the top right-corner of the header, that one clicked on, will open a settings drop-down that will allow you to customize the color of the board squares, or choose a texture for them, like for example, wood, or marble.

Here are some screenshot examples from how lichess.org does it:

<img width="365" alt="Screen Shot 2024-07-14 at 8 34 59 PM" src="https://github.com/user-attachments/assets/2d824fd1-4bc1-49cd-b8b5-7caf796ffdb4">

<img width="503" alt="Screen Shot 2024-07-14 at 8 35 26 PM" src="https://github.com/user-attachments/assets/0bdbad04-432c-48f4-9ad5-aa388a3bff39">

<img width="976" alt="Screen Shot 2024-07-14 at 8 35 53 PM" src="https://github.com/user-attachments/assets/43764b5a-fee9-4d1f-ab6f-aadf426742f1">

**Comment by xa31er** [comment]
on it!

**Comment by Naviary2** [comment]
> on it!

🔥 I've made a list some time ago of colors I thought look good on the infinite board!
https://discord.com/channels/1114425729569017918/1114492409598967819/1168330900732391445

**Comment by Naviary2** [comment]
[This branch](https://github.com/Infinite-Chess/infinitechess.org/tree/themes) is currently working on this feature

**Comment by Naviary2** [comment]
#339 Done!

**Comment by Naviary2** [comment]
I guess textures aren't added, but I don't really have a clue where I'm gonna find good tileable wood/marble board textures so I'll leave them for now
