### ISSUE TITLE
Bug- Newly created accounts are deleted upon server restart for being 'Unverified for more than 3 days'

### ISSUE THREAD

**Issue by Naviary2** [Infinite-Chess/infinitechess.org#91]
..even if they were created 30 seconds ago.

My guess is an issue with this variable in the removeAccounts Controller

<img width="1082" alt="Screen Shot 2024-07-16 at 2 59 50 AM" src="https://github.com/user-attachments/assets/8793f244-8ae6-4e5a-8131-885df40f68e9">

**Comment by tsevasa** [comment]
should be fixed in #92 , the issue seems to be in members.js

**Comment by Naviary2** [comment]
Nice!
